/**
 * RESOURCES
 * 
 * SYSTEM DESIGN FOR A MOBILE BANKING APPLICATION
 * 
 * RESOURCE USER
 * GET, POST, PUT, DELETE
 * CREATE A USER (SIGN UP/REGISTER) /register
 * CHECK IF USER EXIST (LOGIN/SIGN IN) /login
 * UPDATE THEIR DATA (DATA LIKE: PASSWORD, USERNAME, PICTURE....) /user:userId
 * 
 * RESOURCE TRANSACTION
 * GET, POST, PUT, DELETE
 * CREATE A TRANSACTION (DEPOSIT, WITHDRAWAL, TRANSFER)
 * READ TRANSACTIONS (A PARTICULAR USER TRANSACTIONS)
 * READ A TRANSACTION (A PARTICULAR USER TRANSACTION)
 * 
 * 
 * DATABASE MODEL DESIGN
 * TYPES: MVC...
 * USER MODEL
 * _ID: OBJECTID(STRING) 656747458584858GGKJKRGJK
 * EMAIL - STRING, REQUIRED, UNIQUE
 * PASSWORD - STRING, REQUIRED
 * IMAGE: - STRING
 * PIN - NUMBER, REQUIRED
 * PHONENUMBER - NUMBER, REQUIRED, UNIQUE
 * ACCOUNT_NUMBER - NUMBER
 * FIRST_NAME - STRING, REQUIRED
 * LAST_NAME - STRING, REQUIRED
 * BVN - NUMBER
 * SECRET_QUESTION - STRING
 * SECRET_ANSWER - STRING
 * BALANCE - STRING
 * 
 * TRANSACTIONS MODEL
 * _ID: 5567FDJFJJ45GKJKRGJK, OBJECTID
 * TRANSACTION_TYPE - STRING, REQUIRED, ENUM[TRANSFER, WITHDRAWAL, DEPOSIT, BILL]
 * AMOUNT - NUMBER, REQUIRED
 * SENDER_RECEIVER - OBJECTID, 
 * MERCHANT_NAME - STRING
 * USER_ID: OBJECTID, REQUIRED,ID_OF_A_USER_FROM_THE_USER_MODEL(EXAMPLE: 656747458584858GGKJKRGJK)
 */